### ISSUE TITLE
Year abbreviations

### ISSUE THREAD

**Issue by groenroos** [sapegin/textlint-rule-apostrophe#13]
Sometimes years are abbreviated by omitting the first two digits, like so;

    Salesforce Winter ’22
    The Class of ’92
    Summer of ’69

According to [this reference](https://editorsmanual.com/articles/years/#abbreviation), the correct apostrophe to use for these year abbreviations is `’`. However, using `'`, or `‘` doesn't currently trigger an error with this rule.

**Comment by sapegin** [comment]
Hey, I personally dislike them: saving one character is not worth reduced readability. However, feel free to send a pull request with a fix.

**Comment by groenroos** [comment]
@sapegin Agreed, it's not my favourite writing style either - but it's sometimes unavoidable, and I think the linter should pick it up. I've opened #30 to fix this!
