### ISSUE TITLE
Prime characters?

### ISSUE THREAD

**Issue by groenroos** [sapegin/textlint-rule-apostrophe#31]
When researching for #30, I came across another symbol that looks like an apostrophe but isn't: [primes](https://en.wikipedia.org/wiki/Prime_(symbol)).

Their correct use is for:

- Feet and inches (e.g. `6′3`, or `16″`)
- Stopwatch style time notation (e.g. `00′00″000`)
- Latitude and longitude (e.g. `49° 53′ 08″`)

These all use the _single prime_ (`′`), which looks like an apostrophe, and the _double prime_ (`″`), which looks like a quotation mark.

<details>
<summary>Sidenote</summary>
There is also a rare _triple prime_ (`‴`), but I think we can safely ignore this, as it's an esoteric symbol related to watchmaking, and also doesn't look similar to anything else.
</details>

Each of the examples above are ones where an author will often type a straight apostrophe (`'`) and/or a straight quotation mark (`"`) instead of the appropriate prime symbol, out of convenience.

Should this package notice these situations, and suggest the use of the appropriate prime character? Or is this perhaps slightly outside of scope?

**Comment by sapegin** [comment]
I think that would be quite out of the scope ;-)

**Comment by groenroos** [comment]
Fair enough! :)

If I get the time, I'll write a separate rule plugin for prime characters! 👍
